version: "3.3"

services:
    db_identity:
        image: mariadb:10.6
        volumes:
            - data-mariadb-identity:/var/lib/mysql            
        restart: unless-stopped
        environment:
            - MARIADB_RANDOM_ROOT_PASSWORD=yes
            - MARIADB_USER=identity
            - MARIADB_PASSWORD=password
            - MARIADB_DATABASE=identity
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
            
    db_registry:
        image: mariadb:10.6
        volumes:
            - data-mariadb-registry:/var/lib/mysql
        restart: unless-stopped
        environment:
            - MARIADB_RANDOM_ROOT_PASSWORD=yes
            - MARIADB_USER=registry
            - MARIADB_PASSWORD=password
            - MARIADB_DATABASE=registry
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

    phpmyadmin:
        depends_on:
            - db_identity
            - db_registry
        image: phpmyadmin
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            - PMA_HOSTS=db_identity:3306,db_registry:3306

    registry:
        depends_on:
            - db
        image: dronedb/registry
        volumes:
            - ./data/App_Data:/Registry/App_Data
            - ./appsettings.json:/Registry/appsettings.json
            - ./data/logs:/Registry/logs
        ports:
            - 5000:5000
        restart: unless-stopped

volumes:
  data-mariadb-identity:
    driver: local
  data-mariadb-registry:
    driver: local