apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: registry-claim
  name: registry-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-sc-cinderplugin
