name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: setup utils
      run: sudo apt-get update && sudo apt-get install -y spatialite-bin libsqlite3-mod-spatialite
    - name: download ddb
      uses: wei/curl@master
      with:
        args: -fsSL https://get.dronedb.app -o get-ddb.sh
    - name: install ddb
      run: sh get-ddb.sh
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: |        
        export PATH="$HOME/.local/ddb/bin:$PATH"
        echo $PATH
        dotnet test --no-restore --verbosity minimal
